(loop for (mode . ext) in '((emacs-lisp-mode . "\\.el$")
                            (lisp-mode . "\\.\\(cl\\|lisp\\)$")
                            (scheme-mode . "\\.scm$")
                            (clojure-mode . "\\.clj$")
                            (yaml-mode . "\\.ya?ml$")
                            (js2-mode . "\\.js$")
                            (coffee-mode . "\\.coffee$")
                            (org-mode . "\\.org$")
                            (css-mode . "\\.css$")
                            (less-css-mode . "\\.less$")
                            (haml-mode . "\\.haml$")
                            (sass-mode . "\\.sass$")
                            (json-mode . "\\.json$")
                            (php-mode . "\\.php$")
                            (web-mode . "\\.html$")
                            (groovy-mode . "\\.gradle$")
                            (web-mode . "\\.vue$")
                            (json-mode . "\\.json$")
                            (pug-mode . "\\.pug$"))
      do (add-to-list 'auto-mode-alist (cons ext mode)))
